/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myandroidapp_Hello_JNI */

#ifndef _Included_com_example_myandroidapp_Hello_JNI
#define _Included_com_example_myandroidapp_Hello_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myandroidapp_Hello_JNI
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myandroidapp_Hello_1JNI_messageFromNativeCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
