/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myandroidapp_OpenFile_JNI */

#ifndef _Included_com_example_myandroidapp_OpenFile_JNI
#define _Included_com_example_myandroidapp_OpenFile_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myandroidapp_OpenFile_JNI
 * Method:    OpenFile_JNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myandroidapp_OpenFile_1JNI_OpenFile_1JNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
