/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myandroidapp_OpenFileJNI */

#ifndef _Included_com_example_myandroidapp_OpenFileJNI
#define _Included_com_example_myandroidapp_OpenFileJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myandroidapp_OpenFileJNI
 * Method:    OpenFileFunctionJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myandroidapp_OpenFileJNI_OpenFileFunctionJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
