/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myandroidapp_FileOperationJNI */

#ifndef _Included_com_example_myandroidapp_FileOperationJNI
#define _Included_com_example_myandroidapp_FileOperationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myandroidapp_FileOperationJNI
 * Method:    OpenFile
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_myandroidapp_FileOperationJNI_OpenFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_myandroidapp_FileOperationJNI
 * Method:    CloseFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myandroidapp_FileOperationJNI_CloseFile
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myandroidapp_FileOperationJNI
 * Method:    WriteString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_myandroidapp_FileOperationJNI_WriteString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_myandroidapp_FileOperationJNI
 * Method:    ReadString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myandroidapp_FileOperationJNI_ReadString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
